spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  application:
    name: timetable

  datasource:
    url: jdbc:h2:file:./data/timetabledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: tadiwa
    password: 2003
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  resources:
    static-locations: file:./dist/

  mail:
    host: smtp.gmail.com
    port: 587
    username: mytipstadiwa@gmail.com ##for this challenge only
    password: ##place the password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  file-upload:
    location: public/uploads

# --- Logging ---
logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.authentication: DEBUG
        security.web.authentication: DEBUG

# --- JWT Secret Key (FOR THIS CHALLENGE ONLY, REMOVE IN PROD) ---
jwt:
  secret: 83ebc0eba226cd761cdbc2dd78cf1c3ff34ae0488bf3ed4c45d0bb4d95d337ac
